import { test, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import readline from 'node:readline';

let fixture, origin;
test.beforeAll(async()=>{
  fixture=spawn('go',['test','-run','^TestPlaywrightFixture$','-count=1','-v','./internal/ui'],{cwd:process.cwd(),env:{...process.env,LANPANEL_PLAYWRIGHT_FIXTURE:'1'},stdio:['ignore','pipe','pipe']});
  const lines=readline.createInterface({input:fixture.stdout});
  origin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Go UI fixture timeout')),30000);lines.on('line',line=>{const marker='LANPANEL_FIXTURE_ORIGIN=';if(line.includes(marker)){clearTimeout(timer);resolve(line.slice(line.indexOf(marker)+marker.length))}});fixture.once('exit',code=>reject(new Error(`Go UI fixture exited ${code}`)))});
});
test.afterAll(async()=>{if(fixture&&!fixture.killed){fixture.kill('SIGTERM');await new Promise(resolve=>{fixture.once('exit',resolve);setTimeout(resolve,5000)})}});
async function login(page){await page.goto(origin);await page.locator('input[name=token]').fill('admin');await page.locator('button').first().click();await expect(page.locator('#status')).toHaveText('Authenticated')}
test('LP-AUTH-001 real UI stores host-only selector and memory credentials',async({page,context})=>{await login(page);const cookies=await context.cookies();expect(cookies).toHaveLength(1);expect(cookies[0]).toMatchObject({name:'lanpanel_session',httpOnly:true,sameSite:'Strict',secure:false});expect(await page.evaluate(()=>sessionStorage.getItem('lp.proof'))).toHaveLength(64);expect(await page.evaluate(()=>sessionStorage.getItem('lp.csrf'))).toHaveLength(64)});
test('LP-AUTH-002 real UI logout clears selector and browser credentials',async({page,context})=>{await login(page);await page.locator('#logout').click();await page.waitForURL(origin+'/');expect(await context.cookies()).toHaveLength(0);await page.waitForFunction(()=>sessionStorage.length===0)});
test('LP-AUTH-003 real UI Host Origin CSRF and response defenses fail closed',async({request})=>{let bad=await request.post(origin+'/login',{headers:{Origin:'http://127.0.0.1:1','Content-Type':'application/x-www-form-urlencoded'},data:'token=admin'});expect(bad.status()).toBe(403);let response=await request.get(origin+'/',{headers:{Host:'example.invalid'}});expect(response.status()).toBe(421);response=await request.get(origin+'/');expect(response.headers()['cache-control']).toBe('no-store, private');expect(response.headers()['content-security-policy']).not.toContain('unsafe-inline');expect(response.headers()['x-frame-options']).toBe('DENY')});
test('LP-AUTH-004 real UI browser back does not reveal authenticated content',async({page})=>{await login(page);await page.goto('about:blank');await page.goBack();await expect(page.locator('#status')).toHaveText('');expect(await page.evaluate(()=>sessionStorage.length)).toBe(0)});
test('LP-ACTION-001 admin token rotation reviews Plan and invalidates the old session',async({page,context})=>{await login(page);page.once('dialog',async dialog=>{expect(dialog.message()).toContain('admin_token_rotate');expect(dialog.message()).toContain('admin_token_rotation');await dialog.accept()});await page.locator('#rotate').click();await expect(page.locator('#status')).toHaveText('New admin token: new-admin-token');expect(await context.cookies()).toHaveLength(0);expect(await page.evaluate(()=>sessionStorage.length)).toBe(0);await page.locator('input[name=token]').fill('new-admin-token');await page.locator('#login button').click();await expect(page.locator('#status')).toHaveText('Authenticated')});
test('LP-HEADSCALE-001 immutable Headscale initialization requires warning and typed action',async({page})=>{await login(page);const form=page.locator('#headscale-initialize');await form.locator('input[name=control_domain]').fill('control.example.test');await form.locator('input[name=magicdns_namespace]').fill('mesh.example.test');page.once('dialog',async dialog=>{expect(dialog.message()).toContain('cannot be changed or removed');await dialog.accept()});const responsePromise=page.waitForResponse(response=>response.url()===origin+'/api/actions/deploy');await form.locator('button').click();const response=await responsePromise;expect(response.status(),response.request().postData()).toBe(200);await expect(page.locator('#status')).toHaveText('Headscale identity hds_00000000000000000000000000000001 initialized; control service and ingress remain inactive');await expect(form).toBeHidden()});
test('LP-HEADSCALE-002 foreign initialization evidence reports terminal job',async({page})=>{await login(page);const form=page.locator('#headscale-initialize');await form.locator('input[name=control_domain]').fill('foreign.example.test');await form.locator('input[name=magicdns_namespace]').fill('mesh.example.test');await form.locator('input[name=proxy_url]').fill('https://proxy.example.test');page.once('dialog',dialog=>dialog.accept());const responsePromise=page.waitForResponse(response=>response.url()===origin+'/api/actions/deploy');await form.locator('button').click();const response=await responsePromise;expect(response.status()).toBe(409);await expect(page.locator('#status')).toHaveText('Blocked: foreign Headscale database, account, or artifact evidence; job job_foreign_headscale_fixture')});
test('LP-AUTH-005 real UI WebSocket binds selector and first-frame proof',async({page,context})=>{await login(page);const proofA=await page.evaluate(()=>sessionStorage.getItem('lp.proof'));const accepted=await page.evaluate(({origin,proof})=>new Promise(resolve=>{const ws=new WebSocket(origin.replace('http:','ws:')+'/api/events','lanpanel.events.v1');ws.onopen=()=>ws.send(JSON.stringify({type:'auth',proof}));ws.onmessage=event=>{resolve(JSON.parse(String(event.data)).type==='ready');ws.close()};ws.onerror=()=>resolve(false);setTimeout(()=>resolve(false),7000)}),{origin,proof:proofA});expect(accepted).toBe(true);await context.clearCookies();await login(page);const rejected=await page.evaluate(({origin,proof})=>new Promise(resolve=>{let ready=false;const ws=new WebSocket(origin.replace('http:','ws:')+'/api/events','lanpanel.events.v1');ws.onopen=()=>ws.send(JSON.stringify({type:'auth',proof}));ws.onmessage=()=>{ready=true};ws.onclose=()=>resolve(!ready);ws.onerror=()=>resolve(true);setTimeout(()=>resolve(false),7000)}),{origin,proof:proofA});expect(rejected).toBe(true)});
